### ISSUE TITLE
SonarCloud branch page is blank

### ISSUE THREAD

**Issue by rcdailey** [highbyte/sonarscan-dotnet#12]
I followed the instructions in your main `README.md` and ended up with this workflow job (from [this file](https://github.com/rcdailey/trash-updater/blob/sonarcloud/.github/workflows/build.yml#L62)):

```yml
env:
  dotnetVersion: 6.0.x
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: rcdailey_trash-updater
          sonarProjectName: trash-updater
          sonarOrganization: rcdailey
          dotnetBuildArguments: ./src
          dotnetTestArguments: ./src
```

[Here](https://github.com/rcdailey/trash-updater/runs/4171616779?check_suite_focus=true) is the resulting build, which succeeded. However, the [sonarcloud summary page](https://sonarcloud.io/summary/new_code?branch=sonarcloud&id=rcdailey_trash-updater) for that branch shows no issues, and the [code tab](https://sonarcloud.io/code?branch=sonarcloud&id=rcdailey_trash-updater) is blank!

What am I doing wrong?
