### ISSUE TITLE
Specify a project or solution file

### ISSUE THREAD

**Issue by fergek-ms** [highbyte/sonarscan-dotnet#5]
Hi!

I'm trying to send data to my on premise SonarQube using this sonarscan-dotnet.

I'll add here the content of my .YML file

```
name: Static analysis code
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: highbyte/sonarscan-dotnet@1.0
        with:
          sonarProjectKey: prp-be
          sonarProjectName: prp-be
          sonarHostname: https://sonarqube.prdevelopment.net/
```

When the github action runs I can see on the logs the following error:

**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**

Is there anything you see in my YML file that I have to correct to get this working?

Thanks in advance.

**Comment by highbyte** [comment]
If your .NET project or solution file isn't located in the repository root, you need to specify the path to it with the `dotnetBuildArguments` parameter.  See example here:
https://github.com/highbyte/sonarscan-dotnet#build-subfolder-src-and-include-code-coverage

**Comment by highbyte** [comment]
Did you manage to get your action working?

**Comment by SVYSHE** [comment]
I've got the same issue tho. '.sln' file is localized in the repository root but still doesn't work..

**Comment by highbyte** [comment]
It seems you'll need to add a step before sonarscan-dotnet step, to checkout the repo. Otherwise the sonarscan-dotnet step doesn't have access to any source code to build/scan.

```
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: sonarscan-dotnet
      uses: highbyte/sonarscan-dotnet@2.0
      with:
        ...
```
